### ISSUE TITLE
Passing a Buffer to .attach

### ISSUE THREAD

**Issue by mikemorton** [Kong/unirest-nodejs#126]
The following works fine for me:

```.js
  unirest.put(`${URL_BASE}/api/v1/Databases/${DBID}/Records/${RECORDID}/Content/${FIELDID}`)
  .headers({'Content-Type': 'multipart/form-data'})
  .attach('asdf', fs.createReadStream('V:/Multimedia/pumpkins.jpg'))
  .auth({user:USERNAME, pass:PASSWORD})
  .end(function (res) {
    console.log('statusCode:', res && res.statusCode);

    console.log('body:', res.body);
  });
```

However the next thing I'd like to do do is send large uploads in chunks.  I can divide the file into chunks as Buffer objects but sending the buffer to attach does not seem to work for me:

```.js
  var bufferStream = new stream.PassThrough();
  bufferStream.end(Buffer.from(buffer));

  unirest.put(`${URL_BASE}/api/v1/Databases/${DBID}/Records/${RECORDID}/Content/${FIELDID}`)
  .headers({'Content-Type': 'multipart/form-data'})
  .attach('asdf', bufferStream)
  .auth({user:USERNAME, pass:PASSWORD})
  .end(function (res) {
    console.log('statusCode:', res && res.statusCode);

    console.log('body:', res.body);
  });
```
Yields the folowing error:
> TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Length"
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at FormData.<anonymous> (V:\Work\upload test\node_modules\unirest\node_modules\form-data\lib\form_data.js:321:13)
    at V:\Work\upload test\node_modules\unirest\node_modules\form-data\lib\form_data.js:265:7
    at V:\Work\upload test\node_modules\async\lib\async.js:251:17
    at done (V:\Work\upload test\node_modules\async\lib\async.js:126:15)
    at V:\Work\upload test\node_modules\async\lib\async.js:32:16
    at V:\Work\upload test\node_modules\async\lib\async.js:248:21
    at V:\Work\upload test\node_modules\async\lib\async.js:572:34
    at V:\Work\upload test\node_modules\unirest\node_modules\form-data\lib\form_data.js:105:13
    at FSReqWrap.oncomplete (fs.js:153:21)

What is the correct way to send a raw stream to `.attach()` ?

**Comment by Daniyal83** [comment]
I hope someone will answer and solve the issue.

**Comment by huan** [comment]
I run into this issue today with a `Readable` stream.

It seems that we have to use an FS Readable stream for this API method.

It would be great if we could use a Readable stream for this API!

**Comment by huan** [comment]
It turns out that the `unirest` are using the NPM module [form-data](https://github.com/form-data), and the form-data module requires that if it received a stream that not `fs.ReadStream`, we need to provide the file information by additional.

Example:

```ts
form.append( 
  'my_file', 
  stream,
  {
    filename: 'bar.jpg', 
    contentType: 'image/jpeg', 
    knownLength: 19806,
  },
)

```

See: https://github.com/form-data/form-data#void-append-string-field-mixed-value--mixed-options-
